<?php

return [
    'trains' =>  [
        [
            'company' => 'trenitalia',
            'departure_date' => '2024-05-13',
            'departure_station' => 'Rome',
            'arrival_station' => 'Milan',
            'departure_time' => '12:20',
            'arrival_time' => '19:30',
            'train_code' => 'tr4983',
            'carriages_number' => 4,
            'is_on_time' => 1,
            'is_canceled' => 0,
        ],
        [
            'company' => 'sncf',
            'departure_date' => '2024-06-25',
            'departure_station' => 'Paris',
            'arrival_station' => 'Berlin',
            'departure_time' => '08:45',
            'arrival_time' => '15:10',
            'train_code' => 'sn2312',
            'carriages_number' => 6,
            'is_on_time' => 1,
            'is_canceled' => 0,
        ],
        [
            'company' => 'DB Bahn',
            'departure_date' => '2024-07-15',
            'departure_station' => 'Munich',
            'arrival_station' => 'Hamburg',
            'departure_time' => '11:15',
            'arrival_time' => '17:45',
            'train_code' => 'db1937',
            'carriages_number' => 8,
            'is_on_time' => 0,
            'is_canceled' => 1,
        ],
        [
            'company' => 'Eurostar',
            'departure_date' => '2024-08-03',
            'departure_station' => 'London',
            'arrival_station' => 'Brussels',
            'departure_time' => '09:30',
            'arrival_time' => '14:55',
            'train_code' => 'es7531',
            'carriages_number' => 7,
            'is_on_time' => 1,
            'is_canceled' => 0,
        ],
        // Add more trips below with specific values
        [
            'company' => 'Renfe',
            'departure_date' => '2024-09-12',
            'departure_station' => 'Madrid',
            'arrival_station' => 'Barcelona',
            'departure_time' => '14:00',
            'arrival_time' => '18:30',
            'train_code' => 'rn2105',
            'carriages_number' => 5,
            'is_on_time' => 1,
            'is_canceled' => 0,
        ],
        [
            'company' => 'Amtrak',
            'departure_date' => '2024-10-20',
            'departure_station' => 'New York',
            'arrival_station' => 'Washington',
            'departure_time' => '07:45',
            'arrival_time' => '11:20',
            'train_code' => 'am7843',
            'carriages_number' => 6,
            'is_on_time' => 1,
            'is_canceled' => 0,
        ],
        [
            'company' => 'Virgin Trains',
            'departure_date' => '2024-11-08',
            'departure_station' => 'Manchester',
            'arrival_station' => 'Birmingham',
            'departure_time' => '10:10',
            'arrival_time' => '12:55',
            'train_code' => 'vt6218',
            'carriages_number' => 3,
            'is_on_time' => 1,
            'is_canceled' => 0,
        ],
        [
            'company' => 'SJ',
            'departure_date' => '2024-12-05',
            'departure_station' => 'Stockholm',
            'arrival_station' => 'Oslo',
            'departure_time' => '13:20',
            'arrival_time' => '18:45',
            'train_code' => 'sj4456',
            'carriages_number' => 5,
            'is_on_time' => 0,
            'is_canceled' => 1,
        ],
        [
            'company' => 'Thalys',
            'departure_date' => '2025-01-17',
            'departure_station' => 'Brussels',
            'arrival_station' => 'Amsterdam',
            'departure_time' => '10:55',
            'arrival_time' => '13:30',
            'train_code' => 'th6722',
            'carriages_number' => 8,
            'is_on_time' => 1,
            'is_canceled' => 0,
        ],
        [
            'company' => 'TGV Lyria',
            'departure_date' => '2025-02-23',
            'departure_station' => 'Geneva',
            'arrival_station' => 'Zurich',
            'departure_time' => '14:40',
            'arrival_time' => '17:20',
            'train_code' => 'tg8753',
            'carriages_number' => 6,
            'is_on_time' => 0,
            'is_canceled' => 1,
        ],
    ]
];
